function [d,Ms,Ns,x]=leesjpegstruc(f)
% LEESJPEGSTRUCT - Leest structuur (en info) van JPEG-files

% ref : ISO/IEC 10918-1 = 1993(E)

global JPEGMarkers

if isempty(JPEGMarkers)
	JPEGMarkers={	...
			192,'SOF_0',1,'Baseline DCT';	...
			193,'SOF_1',1,'Extended sequential DCT';	...
			194,'SOF_2',1,'Progressive DCT';	...
			195,'SOF_3',1,'Lossless (sequential)';	...
			197,'SOF_5',1,'Differential sequential DCT';	...
			198,'SOF_6',1,'Differential progressive DCT';	...
			199,'SOF_7',1,'Differential lossless (sequential)';	...
			200,'JPG'  ,1,'Reserved for JPEG extensiions (arithmetic)';	...
			201,'SOF_9',1,'Extended sequential DCT (arithmetic)';	...
			202,'SOF_A',1,'Progressive DCT (arithmetic)';	...
			203,'SOF_B',1,'Lossless (sequential) (arithmetic)';	...
			205,'SOF_D',1,'Differential sequential DCT (arithmetic)';	...
			206,'SOF_E',1,'Differential progressive DCT (arithmetic)';	...
			207,'SOF_F',1,'Differential lossless (sequential) (arithmetic)';	...
			196,'DHT'  ,1,'Define Huffman table(s)';	...
			204,'DAC'  ,1,'Define arithmetic coding conditioning(s)';	...
			208,'RST_0',0,'Restart with modulo 8 "0"';	...
			209,'RST_1',0,'Restart with modulo 8 "1"';	...
			210,'RST_2',0,'Restart with modulo 8 "2"';	...
			211,'RST_3',0,'Restart with modulo 8 "3"';	...
			212,'RST_4',0,'Restart with modulo 8 "4"';	...
			213,'RST_5',0,'Restart with modulo 8 "5"';	...
			214,'RST_6',0,'Restart with modulo 8 "6"';	...
			215,'RST_7',0,'Restart with modulo 8 "7"';	...
			216,'SOI'  ,0,'Start of image';	...
			217,'EOI'  ,0,'End of image';	...
			218,'SOS'  ,1,'Start of scan';	...
			219,'DQT'  ,1,'Define quantization tables(s)';	...
			220,'DNL'  ,1,'Define number of lines';	...
			221,'DRI'  ,1,'Define restart interval';	...
			222,'DHP'  ,1,'Define hierarchical progression';	...
			223,'EXP'  ,1,'Expand reference components(s)';	...
			224,'APP_0',1,'Reserved for application segments';	...
			225,'APP_1',1,'Reserved for application segments';	...
			226,'APP_2',1,'Reserved for application segments';	...
			227,'APP_3',1,'Reserved for application segments';	...
			228,'APP_4',1,'Reserved for application segments';	...
			229,'APP_5',1,'Reserved for application segments';	...
			230,'APP_6',1,'Reserved for application segments';	...
			231,'APP_7',1,'Reserved for application segments';	...
			232,'APP_8',1,'Reserved for application segments';	...
			233,'APP_9',1,'Reserved for application segments';	...
			234,'APP_A',1,'Reserved for application segments';	...
			235,'APP_B',1,'Reserved for application segments';	...
			236,'APP_C',1,'Reserved for application segments';	...
			237,'APP_D',1,'Reserved for application segments';	...
			238,'APP_E',1,'Reserved for application segments';	...
			239,'APP_F',1,'Reserved for application segments';	...
			240,'JPG_0',1,'Reserved for JPEG extensions';	...
			241,'JPG_1',1,'Reserved for JPEG extensions';	...
			242,'JPG_2',1,'Reserved for JPEG extensions';	...
			243,'JPG_3',1,'Reserved for JPEG extensions';	...
			244,'JPG_4',1,'Reserved for JPEG extensions';	...
			245,'JPG_5',1,'Reserved for JPEG extensions';	...
			246,'JPG_6',1,'Reserved for JPEG extensions';	...
			247,'JPG_7',0,'Reserved for JPEG extensions';	...	zonder data??
			248,'JPG_8',1,'Reserved for JPEG extensions';	...
			249,'JPG_9',1,'Reserved for JPEG extensions';	...
			250,'JPG_A',1,'Reserved for JPEG extensions';	...
			251,'JPG_B',1,'Reserved for JPEG extensions';	...
			252,'JPG_C',1,'Reserved for JPEG extensions';	...
			253,'JPG_D',1,'Reserved for JPEG extensions';	...
			254,'COM'  ,1,'Comment';	...
			  1,'TEM'  ,0,'For temporary private use in arithmetic coding';	...
		  };
end

markerlijst=cat(1,JPEGMarkers{:,1});

if ischar(f)
	fid=fopen(f);
	if fid<3
	  error('Kan file niet openen');
	end
	x=fread(fid,'*uint8');
	fclose(fid);
else
	x=f(:);
end
x=double(x);	% omdat de rest niet werkt met uint8!!

i=find(x(1:end-1)==255&x(2:end)>0&x(2:end)<255);
M=x(i+1);
markers=unique(M);
n=hist(double(M),double(markers));
d=struct('marker',num2cell(M),'len',-1,'markerName','???','data',[],'index',num2cell(i));
imax=0;
dumTag=true(length(i),1);
for j=1:length(i)
	k=find(markerlijst==M(j));
	if i(j)<imax
		%dumTag(j)=true;
	elseif ~isempty(k)
		dumTag(j)=false;
		d(j).markerName=JPEGMarkers{k,2};
		if JPEGMarkers{k,3}
			d(j).len=double(x(i(j)+2))*256+double(x(i(j)+3));
			if d(j).len+i(j)+1>length(x)
				fprintf('!!!!!fout met lengte (marker %d)\n',j);
			else
				imax=i(j)+d(j).len+1;
				d(j).data=x(i(j)+4:imax)';
			end
		elseif strcmp(d(j).markerName,'EOI')	% stop reading
			if length(x)-i(j)>10
				if x(i(j+1)+1)==216	% second SOI!
					warning('Extra JPEG-block after the main JPEG-block!')
				else
					warning('Extra bytes in JPEG-file (#%d)\n',length(x)-i(j)-1)
				end
			end
			break
		end
	end
end
if any(dumTag)
	d(dumTag)=[];
end
if nargout>1
	Ms=markers;
	if nargout>2
		Ns=n;
	end
end

