function FIB_s=readwdoc(f)
% READWDOC - Word document reader (start)

fid=fopen(f,'r');
if fid<3
	error('File kan niet geopend worden');
end

tekst=fread(fid);
fclose(fid);

%main stream
%summary information stream
%table stream
%data stream
%n object streams

%PN pagenumber (512 byte)

le16=[1 256];
le32=[1 256 65536 16777216];

% FIB (file information block)
FIB=tekst(513:1024);
wIdent=le16*FIB(1:2);	% FIB header magic number
nFib=le16*FIB(3:4);
nProduct=le16*FIB(5:6);
lid=le16*FIB(7:8);
pnNext=le16*FIB(9:10);
cInfo=le16*FIB(11:12);
isTemplate=bitand(cInfo,1);
isGlsy=bitand(cInfo,2);
isComplex=bitand(cInfo,4);
isHasPic=bitand(cInfo,8);
nQuickSaves=bitand(cInfo,16*15);
isEncrypted=bitand(cInfo,256);
whichTable=bitand(cInfo,512);
isReadOnlyRec=bitand(cInfo,1024);
isWriteReserve=bitand(cInfo,2048);
isExtChar=bitand(cInfo,4096);
isLoadOverride=bitand(cInfo,8192);
isFarEast=bitand(cInfo,16384);
isCrypto=bitand(cInfo,32768);
nFibBack=le16*FIB(13:14);
lKey=le32*FIB(15:18);
envr=FIB(19);
cInfo2=FIB(20);
fMac=bitand(cInfo2,1);
fEmptySpecial=bitand(cInfo2,2);
fLoadOverridePage=bitand(cInfo2,4);
fFutureSavedUndo=bitand(cInfo2,8);
fWord97Saved=bitand(cInfo2,16);

FIB_s=struct('wIdent',wIdent	...
	,'nFib',nFib	...
	,'nProduct',nProduct	...
	,'lid',lid	...
	,'pnNext',pnNext	...
	,'cInfo',cInfo	...
	,'isTemplate',isTemplate	...
	,'isGlsy',isGlsy	...
	,'isComplex',isComplex	...
	,'isHasPic',isHasPic	...
	,'nQuickSaves',nQuickSaves	...
	,'isEncrypted',isEncrypted	...
	,'whichTable',whichTable	...
	,'isReadOnlyRec',isReadOnlyRec	...
	,'isWriteReserve',isWriteReserve	...
	,'isExtChar',isExtChar	...
	,'isLoadOverride',isLoadOverride	...
	,'isFarEast',isFarEast	...
	,'isCrypto',isCrypto	...
	,'nFibBack',nFibBack	...
	,'lKey',lKey	...
	,'envr',envr	...
	,'cInfo2',cInfo2	...
	,'fMac',fMac	...
	,'fEmptySpecial',fEmptySpecial	...
	,'fLoadOverridePage',fLoadOverridePage	...
	,'fFutureSavedUndo',fFutureSavedUndo	...
	,'fWord97Saved',fWord97Saved	...
	);


fprintf('%s : ident %d FIB %d Prod %d lid %d next %d %04x\n',f,wIdent,nFib,nProduct,lid,pnNext,cInfo)
if isEncrypted
	fprintf('    !!encrypted (%d)\n',lKey);
elseif lKey
	fprintf('    ????key %d\n',lKey)
end
fprintf('    FIBback %d envr %d cInfo2 %d\n',nFibBack,envr,cInfo2)
